# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: game.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto


class Retcode(betterproto.Enum):
    SUCCESS = 0
    ERROR = 1
    # Shop
    NOT_ENOUGH_CURRENCY = 2
    ITEM_ALREADY_BOUGHT = 3
    ITEM_NOT_FOUND = 4


@dataclass
class Record(betterproto.Message):
    player_info: "PlayerBasicInfo" = betterproto.message_field(1)
    player_cur_data: "PlayerCurrentData" = betterproto.message_field(2)
    last_save_timestamp: int = betterproto.int64_field(3)


@dataclass
class PlayerBasicInfo(betterproto.Message):
    pid: str = betterproto.string_field(1)
    name: str = betterproto.string_field(2)
    create_time: int = betterproto.int64_field(3)


@dataclass
class PlayerCurrentData(betterproto.Message):
    hero_id: int = betterproto.uint32_field(1)
    level: int = betterproto.uint32_field(2)
    hp: int = betterproto.uint32_field(3)
    exp: int = betterproto.uint32_field(4)
    weapon_id: int = betterproto.uint32_field(5)
    room_info_list: List["RoomData"] = betterproto.message_field(6)
    shop_info: "ShopData" = betterproto.message_field(7)
    minigame_info_list: List["MinigameData"] = betterproto.message_field(8)


@dataclass
class RoomData(betterproto.Message):
    id: int = betterproto.uint32_field(1)
    finished: bool = betterproto.bool_field(2)


@dataclass
class ShopData(betterproto.Message):
    owned_currency: int = betterproto.uint32_field(1)
    bought_items: List[int] = betterproto.uint32_field(2)


@dataclass
class MinigameData(betterproto.Message):
    id: int = betterproto.uint32_field(1)
    finished: bool = betterproto.bool_field(2)
